apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-app
  namespace: test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-boot-app
  template:
    metadata:
      labels:
        app: spring-boot-app
    spec:
      containers:
        - name: spring-boot-app
          image: akashj08/sprint-boot-app-ci-cd:22
          ports:
            - containerPort: 8080
          imagePullPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: spring-boot-app
  namespace: test
spec:
  selector:
    app: spring-boot-app
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer         